from . import sale_order_approval
from . import sale_order_pricing
from . import sale_order_invoicing
from . import sale_order_portal_report
from . import sale_order_line
from . import report_router
from . import wizards
from . import account_move
from . import rent_tags
from . import rental_invoiced_period
from . import rental_occupant
from . import product_template
